

import { Toaster } from "react-hot-toast";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "@/components/shared/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* ADD suppressHydrationWarning HERE TOO */}
      <body suppressHydrationWarning> 
        <Providers>
          <Navbar/>
          <main>{children}</main>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
